# Generated by Django 5.1.3 on 2024-12-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperience',
            old_name='description',
            new_name='descriptions',
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
